version: "3.1"

volumes:
    db-data:

services:
  apl:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        app_port: ${NODEJS_PORT}
        debug_port: ${DEBUG}
    command: npm run start
    container_name: apl
    restart: always
    volumes:
      - ./src:/app/apl/src
    ports:
      - "${SEVER_PORT}"
      - "${DEBUG_PORT}"